// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soxkzvalqdgaxcytbgpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNveGt6dmFscWRnYXhjeXRiZ3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MzU2MzQsImV4cCI6MjA2MzAxMTYzNH0.W6IBo2bDbIHusrak9cxudu8BVggRl7UdBNC9SKEz-nQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);